### ISSUE TITLE
Add Filename Argument?

### ISSUE THREAD

**Issue by steverinn** [fsoubelet/Timeline#4]
Might we consider adding a Click command line parameter to control the output filename? It'd be useful if that name wasn't hard-coded. I'm happy to fork the repo and make the change myself if you prefer.

That change might look something like:

```
--output-filename FILENAME  Name of output filename. Defaults to timeline.svg.
```

**Comment by fsoubelet** [comment]
Hi @steverinn,

I would be ok with actually changing the outputpath parameter to outputfile directly, which would be a file path type (same as inputfile) and just use that. 

Not sure what I was thinking leaving the directory up to the user and not the file itself.

**Comment by steverinn** [comment]
> Hi @steverinn,
> 
> I would be ok with actually changing the outputpath parameter to outputfile directly, which would be a file path type (same as inputfile) and just use that.
> 
> Not sure what I was thinking leaving the directory up to the user and not the file itself.

I had wondered the same thing, but I figured there was some "typical" use case being covered that explained it. My use case is that I want to call this multiple times with separate inputs, and it's inconvenient to have the outputs clobber each other. So yeah, your suggestion would be just fine.

**Comment by fsoubelet** [comment]
Hi again @steverinn, you can now install a new version from `PyPI` with this option :)
